### ISSUE TITLE
[Discuss] Update NotebookOp to use init containers to handle pre-installation of dependencies

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/kfp-notebook#16]
We are currently using a bootstrap script that gets pulled in via the curl utility, to install our dependencies. This has the disadvantage that the curl utility must be available on all images being used in the pipeline, will become more prevalent when users start bringing in their own images and forget to include it as part of their container
We should instead use init containers to pull the script into a volume that can then be mounted to the main application container. This also has the potential of eliminating the need for us to install python packages... by including a volume with python libraries and appending the location to the PYTHON_PATH env.

**Comment by kevin-bates** [comment]
I really like the idea of using an init container to alleviate dependency issues.  

Regarding this...
>This also has the potential of eliminating the need for us to install python packages... by including a volume with python libraries and appending the location to the PYTHON_PATH env.

I'm a little concerned that massaging [`PYTHONPATH`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) may prove difficult and introduces the question of whether the new location should be prepended or appended to the container's PYTHONPATH.  If we did take this approach and can ensure that no funny business arises with altering the PYTHONPATH, I think we'd want to _prepend_ the init container's offering to the runtime container's PYTHONPATH to ensure we're getting the package versions we expect.  

If we didn't take the PYTHONPATH approach, the init container could still "deploy" the bootstrapper (and any auxiliary files it might need) and have the bootstrapper invoked by CMD - is that right?

**Comment by akchinSTC** [comment]
Correct, we would still be able deploy the bootstrapper script and invoke thru CMD. The PYTHONPATH issue should be hammered out it in more detail so we know all the caveats associated. I plan on starting a POC branch of sorts as a base and we can go from there

**Comment by akchinSTC** [comment]
Have an initial working prototype in these two branches :
https://github.com/akchinSTC/elyra-1/tree/akchin-init
https://github.com/akchinSTC/kfp-notebook/tree/akchin-init
I leverage the kfp dsl to create a new volume op and mount that to each notebook op that runs, the init populates it with our bootscript. It works but need to figure out the garbage collection since the pvcs dont get deleted. 
Theres another angle im working to use emptydirs volume to handle the cleanup since they only exist for the lifetime of the pod. 
![image](https://user-images.githubusercontent.com/13340013/81635320-cfa8ad80-93c5-11ea-91b1-e7280ca8d0b5.png)

**Comment by kevin-bates** [comment]
I think we want to use the opportunity of init-containers to move away from using `curl` and the need to hit some github branch to get the bootstrapper and requirements: https://github.com/akchinSTC/kfp-notebook/blob/akchin-init/notebook/pipeline/_notebook_op.py#L117-L122

Instead, it seems like maintaining our own, extremely simple, image would be better.  This image contains the bootstrapper.py and requirements.txt files along with a script to copy those two files to a shared location (i.e., that the primary container knows about).  Then, the command for the primary container runs the bootrapper file referencing the requirements file.

Dev builds that make changes to either of those two files would just build a dev image and use that.  As a result, we should have a way to specify the tag (and possibly image name) of the init-container.

Since the primary image still runs bootstrapper.py, the PYTHONPATH issue falls out since the single python env will be updated.

Thoughts?
