### ISSUE TITLE
Add ability to set how often the docker image should be downloaded

### ISSUE THREAD

**Issue by lresende** [elyra-ai/kfp-notebook#21]
When Bring Your Own image, sometimes you might be still building the docker image and need to have KFP to always download new images.

**Comment by kevin-bates** [comment]
This option is available as a container argument `image_pull_policy` on the `ContainerOp`.  The default is `IfNotPresent` so we'd need the ability to set `Always`.

I think the bigger question is _where_ will this value come from?  Intuitively, it seems reasonable to have this be a field in the `runtime-images` metadata.  But there are two issues with that:
1. We currently set the actual image_name:tag in the pipeline information, so elyra (where this information is required) has no way to definitively locate the runtime-images metadata instance to get the pull policy from.
2. If there are multiple nodes in the pipeline using this image, do you really want the execution of every node to pull the image?  I suspect you'd only want the image pulled if the downstream node in the pipeline is not running on the same machine.

I think instead, you'd want this property set at the UI level since the user knows which of the nodes first uses the Docker image in question.  But again, the converse of 2 is a question, what about the downstream nodes running on different hosts?
Hmm - I guess you'd want the image always updated - even if the current node is colocated with its upstream node using the same image - and just hope the always-pull logic does a SHA comparison (which I suspect it does) so as to not incur that overhead.

So item 2 can be resolved as a non-issue (with the assumption that the pull policy logic is efficient).  Item 1 should be addressed by using the runtime-images _name_ rather than its `image_name` field within the pipeline and let Elyra lookup the runtime-images instance to get both `image_name` and its `pull_policy` values.

Thoughts?
