### ISSUE TITLE
Bootstrapper should support running `python3` commands

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/kfp-notebook#49]
Refer to https://github.com/elyra-ai/elyra/issues/901#issuecomment-700985095 for background information. In a nutshell, the bootstrapper currently assumes that a compatible Python 3 interpreter is callable by invoking `python`. In environments where `python` resolves to an interpreter version that is unsupported, the bootstrapper will fail. This renders Docker images unusable where the Python 3 interpreter is sym-linked to `python3`.

**Comment by lresende** [comment]
My understanding is that python should be pointing to the `latest python`:

Mac + Anaconda
```
 ls -la ~/opt/anaconda/bin | grep python
lrwxr-xr-x    1 lresende  staff     9B Jul 24 23:09 python -> python3.8
lrwxr-xr-x    1 lresende  staff     9B Jul 24 23:09 python3 -> python3.8
```

Linux + Tensorflow image
```
root@dc3ffd52b000:/# ls -la /usr/local/bin | grep python
lrwxrwxrwx 1 root root   16 Jan 27  2020 python -> /usr/bin/python3
```

What are we suggesting here? 
- Always use `python3` as the command to run python?
- Document our minimum requirement for python?
- Something else?

**Comment by ptitzler** [comment]
> Always use python3 as the command to run python?

Yes. In search of guidance I found https://www.python.org/dev/peps/pep-0394/. Note that there is no requirement for distributors to provide a `python`  command, whereas there is for `python3`:

![image](https://user-images.githubusercontent.com/13068832/94690213-ac36be80-02e4-11eb-87c9-7118f1428e25.png)


> Document our minimum requirement for python?

Already taken care of in https://github.com/elyra-ai/elyra/pull/945

**Comment by kevin-bates** [comment]
Excellent find Patrick.

It should also be noted that because our [image validation explicitly looks for `python3` on the command line](https://github.com/elyra-ai/elyra/issues/901#issuecomment-701036667) it's best that we update the bootstrapper's "bootstrap" command to use `python3` as well.  However, Patrick's information above confirms that that is a safe thing to do.  (FWIW, the cluster I use for EG/YARN testing has both `python` and `python3` with the former linked to `python2`.)
